version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-for-microservices
    ports:
      - "27018:27017"
    environment:
      MONGO_INIT DB_ROOT_USERNAME: root
      MONGO_INIT DB_ROOT_PASSWORD: password
      MONGO_INIT DB DB_DATABASE: product-service
    volumes:
      - ./data:/data/db

